### ISSUE TITLE
Divide by Zero (Exercise 3)

### ISSUE THREAD

**Issue by jessestauffer** [jdwittenauer/ipython-notebooks#8]
Love these machine learning exercises! Just completed exercise 3 but came across one issue in the regularized cost function. I'm getting a divide by 0 error in the `second` var. I assumed this is because log(0) is undefined. Any way around this?

When i compile w/ Python 2.7 the accuracy is around 97% but only 76% when compiled with Python 3.

**Comment by abi98213** [comment]
same problem!

**Comment by AhmedGabal** [comment]
what is the problem Mohamed i don't understand this massage .
and i entered the Github found the solution and i don't understand the
problem.

On Fri, Jan 26, 2018 at 9:12 AM, Muhammad Abdullah <notifications@github.com

**Comment by AhmedGabal** [comment]
are you finished 4 tasks ?

**Comment by Karthikb1999** [comment]
> Love these machine learning exercises! Just completed exercise 3 but came across one issue in the regularized cost function. I'm getting a divide by 0 error in the `second` var. I assumed this is because log(0) is undefined. Any way around this?
> 
> When i compile w/ Python 2.7 the accuracy is around 97% but only 76% when compiled with Python 3.

did u find the solution?iam facing the same problem
